[package]
name = "switch-jni"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ['cdylib']

[dependencies]
switch = {path="../switch"}
jni = "0.20.0"
anyhow = "1.0.65"